### ISSUE TITLE
Problem with links

### ISSUE THREAD

**Issue by ehlersd** [dfmuir/KINWebBrowser#10]
I'm having a problem with two links that seem to be related to the WKWebView change in the latest pod version.

Specifically, the "location/map" button and the "phone" button both have stopped responding:

http://appviews.gatewaypeople.com/campus-locations

Any help would be appreciated.  Thx!

**Comment by dfmuir** [comment]
I believe this issue has been resolved in KINWebBrowser 1.2.0
