### ISSUE TITLE
crach when i press refresh and the page didnt load yet

### ISSUE THREAD

**Issue by syrakozz** [dfmuir/KINWebBrowser#11]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fd9f3f5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010fa38bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010fc658b8 -[__NSPlaceholderArray initWithObjects:count:] + 360
	3   CoreFoundation                      0x000000010fcc4a24 +[NSArray arrayWithObjects:count:] + 52
	4   islami                              0x000000010bc7c866 __51-[KINWebBrowserViewController actionButtonPressed:]_block_invoke + 230
	5   libdispatch.dylib                   0x0000000110d5fcc6 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x0000000110d7d7f4 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000110d66991 _dispatch_main_queue_callback_4CF + 956
	8   CoreFoundation                      0x000000010fd07569 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	9   CoreFoundation                      0x000000010fcca46b __CFRunLoopRun + 2043
	10  CoreFoundation                      0x000000010fcc9a06 CFRunLoopRunSpecific + 470
	11  GraphicsServices                    0x0000000111f549f0 GSEventRunModal + 161
	12  UIKit                               0x000000010e131550 UIApplicationMain + 1282
	13  islami                              0x000000010bb7b8d3 main + 115
	14  libdyld.dylib                       0x0000000110db2145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dfmuir** [comment]
I believe that this issue has been resolved in KINWebBrowser 1.3.0. Check it out!
