### ISSUE TITLE
Class methods don't encourage subclassing

### ISSUE THREAD

**Issue by colinta** [dfmuir/KINWebBrowser#20]
Instead of 

```objc
+ (UINavigationController *)navigationControllerWithWebBrowser {
    KINWebBrowserViewController *webBrowserViewController = [[KINWebBrowserViewController alloc] initWithConfiguration:nil];
    return [self navigationControllerWithBrowser:webBrowserViewController];
}
```

If this was, instead:

```objc
+ (UINavigationController *)navigationControllerWithWebBrowser {
    KINWebBrowserViewController *webBrowserViewController = [[self alloc] initWithConfiguration:nil];
    return [self navigationControllerWithBrowser:webBrowserViewController];
}
```

Then subclasses of `KINWebBrowserViewController` would be returned from these methods.

**Comment by colinta** [comment]
I'll gladly write a PR for this if you think it's a good idea, but I don't want to maintain my own fork.

**Comment by dfmuir** [comment]
Good call. I would merge this PR.

**Comment by dfmuir** [comment]
I went ahead an implemented this. Your suggestions are part of KINWebBrowser 1.2.3.

Let me know what you think,

**Comment by colinta** [comment]
Looks like you already did! :-D

Thanks for adding support. Excellent library!
