### ISSUE TITLE
What about AppStore submission?

### ISSUE THREAD

**Issue by EvgenyKarkan** [dfmuir/KINWebBrowser#30]
Hi @dfmuir 
I'm gonna use KINWebBrowser in my app, but one thing is interesting.
Do it uses any private APIs or another 'dirty' tricks that may cause app rejection during AppStore submission? 
Best

**Comment by dfmuir** [comment]
There are no private APIs used. As far as I know there are no "dirty tricks".

I have multiple apps on the app store that integrate this library. I have never seen a single issue with submission.

Integrate KINWebBrowser into your app with confidence.

**Comment by EvgenyKarkan** [comment]
Thanks.
