### ISSUE TITLE
iOS9: Share button crash + several runtime warnings

### ISSUE THREAD

**Issue by ntnmrndn** [dfmuir/KINWebBrowser#33]
It looks like a few API rules have changed with iOS 9, which leads to a crash when users press the share button.

I'll try to find some time to submit a PR next week

    transform-only layer, will have no effect
    2015-08-13 15:52:54.393 itooch-awsome-project[66203:13062248] -canOpenURL: failed for URL: "about:blank" - error: "This app is not allowed to query for scheme about"
    2015-08-13 15:53:03.061 itooch-awsome-project[66203:13062248] -canOpenURL: failed for URL: "googlechrome-x-callback://" - error: "This app is not allowed to query for scheme googlechrome-x-callback"
    2015-08-13 15:53:03.133itooch-awsome-project[66203:13062248] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x0000000106aeb9b5 __exceptionPreprocess + 165
    	1   libobjc.A.dylib                     0x0000000106173deb objc_exception_throw + 48
    	2   CoreFoundation                      0x0000000106aeb8ed +[NSException raise:format:] + 205
    	3   Foundation                          0x0000000105dade0f -[NSBundle initWithURL:] + 87
    	4   Foundation                          0x0000000105dadebe +[NSBundle bundleWithURL:] + 45
    	5   TUSafariActivity                    0x0000000105c684e3 -[TUSafariActivity activityTitle] + 147
    	6   UIKit                               0x00000001081393d6 -[UIActivityGroupViewController _titleTextForActivity:] + 125
    	7   UIKit                               0x000000010813a570 -[UIActivityGroupViewController collectionView:layout:preferredSizeForItemAtIndexPath:] + 65
    	8   UIKit                               0x000000010847bbd3 __81-[_UIActivityGroupViewFlowLayout _evaluatePreferredItemSizeForItemsAtIndexPaths:]_block_invoke + 40
    	9   CoreFoundation                      0x0000000106a1a552 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
    	10  CoreFoundation                      0x0000000106a19c6f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 239
    	11  UIKit                               0x000000010847bb1c -[_UIActivityGroupViewFlowLayout _evaluatePreferredItemSizeForItemsAtIndexPaths:] + 291
    	12  UIKit                               0x000000010847a8d1 -[_UIActivityGroupViewFlowLayout prepareLayout] + 130
    	13  UIKit                               0x000000010841c31d -[UICollectionViewData _prepareToLoadData] + 67
    	14  UIKit                               0x000000010841caa6 -[UICollectionViewData validateLayoutInRect:] + 53
    	15  UIKit                               0x00000001083ce1a9 -[UICollectionView layoutSubviews] + 196
    	16  UIKit                               0x0000000107c94a3b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
    	17  QuartzCore                          0x0000000107aa236a -[CALayer layoutSublayers] + 146
    	18  QuartzCore                          0x0000000107a96bd0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    	19  UIKit                               0x0000000107c853d8 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1083
    	20  UIKit                               0x0000000108492968 __45-[_UIAnimationCoordinator animateTransition:]_block_invoke + 32
    	21  UIKit                               0x0000000107c8b700 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 582
    	22  UIKit                               0x0000000107c8b9d0 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:] + 187
    	23  UIKit                               0x0000000108492911 -[_UIAnimationCoordinator animateTransition:] + 471
    	24  UIKit                               0x000000010849225e -[_UIAnimationCoordinator animate] + 165
    	25  UIKit                               0x0000000107ee4c4c -[UIAlertController _contentViewControllerWillTransitionToSize:withAnimations:] + 1071
    	26  UIKit                               0x00000001085247a2 -[_UIAlertControllerView _sizeOfContentViewControllerChanged] + 1009
    	27  UIKit                               0x0000000107ee1792 -[UIAlertController viewDidLoad] + 659
    	28  UIKit                               0x0000000107d6dd05 -[UIViewController loadViewIfRequired] + 877
    	29  UIKit                               0x0000000107d6e054 -[UIViewController view] + 27
    	30  UIKit                               0x0000000108485885 -[UIActivityViewController viewDidLoad] + 1266
    	31  UIKit                               0x0000000107d6dd05 -[UIViewController loadViewIfRequired] + 877
    	32  UIKit                               0x0000000107d6e054 -[UIViewController view] + 27
    	33  UIKit                               0x0000000107d878b2 -[UIViewController _setPresentationController:] + 100
    	34  UIKit                               0x0000000107d7edfc -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1437
    	35  UIKit                               0x0000000107d8097c -[UIViewController _presentViewController:withAnimationController:completion:] + 4682
    	36  UIKit                               0x0000000107d834b3 -[UIViewController presentViewController:animated:completion:] + 343
    	37  UIKit                               0x000000010836b54f -[UIPopoverController presentPopoverFromBarButtonItem:permittedArrowDirections:animated:] + 271
    	38  KINWebBrowser                       0x0000000105955bfa __51-[KINWebBrowserViewController actionButtonPressed:]_block_invoke + 954
    	39  libdispatch.dylib                   0x00000001096dffad _dispatch_call_block_and_release + 12
    	40  libdispatch.dylib                   0x00000001097004bb _dispatch_client_callout + 8
    	41  libdispatch.dylib                   0x00000001096e83ff _dispatch_main_queue_callback_4CF + 1738
    	42  CoreFoundation                      0x0000000106a4be69 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    	43  CoreFoundation                      0x0000000106a0d3b9 __CFRunLoopRun + 2073
    	44  CoreFoundation                      0x0000000106a0c918 CFRunLoopRunSpecific + 488
    	45  GraphicsServices                    0x000000010b167ad2 GSEventRunModal + 161
    	46  UIKit                               0x0000000107be799e UIApplicationMain + 171
    	47  itooch-messenger                    0x000000010469d19d main + 109
    	48  libdyld.dylib                       0x000000010973592d start + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by EvgenyKarkan** [comment]
I guess this is because of new changes in iOS 9 with URL schemes.

**Comment by dfmuir** [comment]
Are you still seeing these issues with 1.3.2. I believe that the latest changes to ARChromeActivity should address this. Let me now.

**Comment by ntnmrndn** [comment]
It does fix it, we can close the issue :)
