### ISSUE TITLE
iOS 9: Progress view doesn't work

### ISSUE THREAD

**Issue by EvgenyKarkan** [dfmuir/KINWebBrowser#37]
To reproduce it - just try to load web page under iOS 9. 
UIProgressView instance is hidden, so UX is bad while user waiting for the web content.
I guess this is because of something weird issue with KVO-ing 'estimatedProgress' property on WKWebView. Note that fake progress view also doesn't work with UIWebView.

**Comment by dfmuir** [comment]
I am not able to recreate this. The progress view is working as best that I can tell. How does it work for you in the example project?

**Comment by EvgenyKarkan** [comment]
Hello @dfmuir.
I'm running demo example on iOS 9.1 - everything works great. 
Thanks
Will try to figure it out how can I break it in my project :)
