### ISSUE TITLE
iOS 9 App transport security

### ISSUE THREAD

**Issue by mkeremkeskin** [dfmuir/KINWebBrowser#38]
Hi;

I could not get it work with iOS 9. HTTP links doesn't work. 

I've added the property below to my plist file it also didn't help.

    <key>NSAllowArbitraryLoads</key>
    <true/>
Do you have any idea about this problem?

**Comment by namannik** [comment]
I was also getting an `NSURLErrorDomain` error code `-1022`.  I fixed it by adding the `NSAllowArbitraryLoads` Boolean within the `NSAppTransportSecurity` Dictionary in my app's info.plist.  Below is the structure of this part of the .plist.

![screen shot 2015-09-30 at 8 57 19 am](https://cloud.githubusercontent.com/assets/4149561/10198532/51a75a44-6751-11e5-8b92-16385c14c6aa.png)

Here's the documentation from Apple regarding this new feature:

https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html#//apple_ref/doc/uid/TP40016240

Also, a video from WWDC this year discussing App Transport Security:

https://developer.apple.com/videos/wwdc/2015/?id=711

**Comment by mkeremkeskin** [comment]
It was my that it doesn't work with `NSAllowArbitraryLoads` because I forgot to write s of allows as you can see.

**Comment by dfmuir** [comment]
If you are having issues with HTTP links in KINWebBrowser, add this to your Info.plist file

<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
